### ISSUE TITLE
DOC: List of TODOs for the documentation

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/peft#1089]
### Feature request

This issue serves to list areas in which the documentation can be improved. It can be extended in the future if we find more gaps.

Contributions are welcome, if you want to pick up one of the open topics, let us know beforehand so that we can avoid duplicate work.

- [x] Conceptual guides:
  - [x] Multitask prompt tuning (#400)
  - [x] LoHa (#956)
  - [x] LoKr (#978)
  - [x] AdaLoRA
- [x] Low level API: Activating multiple adapters (#873)
- [x] Quantization: Having a chapter on quantization would be useful (how can it help, what is needed, how to use it, which tuners support it) - assigned to @stevhliu (#1220)
  - [x] QLoRA
  - [x] LoftQ: LoRA initialization for quantized models (#1150) - done (#1218) but could be cross-referenced in quantization section
- [x] Docstrings for each important, user facing method/function - done (#1201)

### Motivation

Better docs, happier users.

### Your contribution

Possible.

**Comment by aldakata** [comment]
Wouldn't this [PR](https://github.com/huggingface/transformers/commit/bd50402b56980ff17e957342ef69bd9b0dd45a7b#diff-aacce60a3f0e53d58f16eb93e1142cf8a1a503868a41084de847465f26382f64) in /transformers close Quantization docs issue?

**Comment by BenjaminBossan** [comment]
Thanks for the pointer. I think it would be good to link there, but I'd also like to see a PEFT-specific section on quantization in the PEFT docs.

**Comment by dame-cell** [comment]
Hi,

 I'm interested in contributing to the project and would like to write documentations but only for quantization for now. 

I've outlined an initial structure for the documentation, covering topics such as:

- Introduction to Quantization
- Benefits of Quantization
- How to Use Quantization in the Project
- Supported Tuners for Quantization
- Examples and Best Practices

I'd love to get your thoughts on this, and if there are specific guidelines or preferences for documentation, please let me know. I'm looking forward to working with the community to enhance the project's documentation.

**Comment by dame-cell** [comment]
hey @BenjaminBossan  just got done writing it , I've just submitted a pull request  hopefully that's enough if you need more please tell me , I'll make sure to make it better

**Comment by younesbelkada** [comment]
@BenjaminBossan seems everything has been addressed, what about closing the issue?

**Comment by BenjaminBossan** [comment]
I'd still like to add (or have contributions for) LoHa, LoKr, OFT in the conceptual guides.

**Comment by BenjaminBossan** [comment]
Done. Thanks so much to everyone involved, especially @stevhliu.
