### ISSUE TITLE
Increase speed of adapter layer initialization

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/peft#896]
### Feature request

We are working on increasing the speed of adapter layer initialization. The first step towards this is #887, which tackles linear LoRA layers, which are arguably the most important ones. As discussed with @pacman100, after that PR, there are still some TODOs:

- [x] apply to Embedding and Conv2d layers (#915)
- [x] apply to compressed layer types, like Linear4bit, Linear8bit (#994)
- [ ] init LoRA modules (A, B) right on target device, not CPU (won't fix for the time being, seems pretty fast already with all the other changes)
- [x] same for AdaLora (#1106)
- [x] same for IA³ (#1106)
- [x] Init in `merge_and_unload` (#1106)

### Motivation

Initial testing showed ~10x increase in speed with the optimized initialization.

### Your contribution

#887 is the first step.

**Comment by BenjaminBossan** [comment]
Not stale

**Comment by osmalpkoras** [comment]
Hi guys, I am trying to load a `meta-llama/Meta-Llama-3-70B-Instruct` PEFT model with `LoraConfig(init_lora_weights="pissa", 16, 0.1, 64, none", CAUSAL_LM", target_modules="all-linear")` and I noticed that it is very slow in initializing the layers. To be precise, it's the `for key in key_list` loop in `peft.tuners.tuners_utils.BaseTuner.inject_adapter` that is very slow. 

Should this issue be actually fixed with these PR's? Because if it should be, than it does not work for `meta-llama/Meta-Llama-3-70B-Instruct` with the above LoraConfig.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this. Is it still slow when you remove `init_lora_weights="pissa"` from the config?

**Comment by osmalpkoras** [comment]
Actually if I use the default method, it is very fast. Switching to `init_lora_weights="pissa_niter_32"` also made it very fast. I just notice that if I use this initialization with a multi-gpu deepspeed setup, it again takes a couple of hours, maybe due to some concurrency issues.

**Comment by BenjaminBossan** [comment]
It is expected that using the default init or PiSSA with `n_iter` is faster than just `pissa`. However, a couple of hours still sounds excessive. Does it finish after a couple of hours or do you just cancel the process at that point?
